spring:
  datasource:
    password: ''
    url: jdbc:mysql://localhost:60298/wxdc?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    password: admin
    port: 5672
    username: admin
  redis:
    host: 192.168.25.121
    password: ''
    port: 6379
